### ISSUE TITLE
EikonGetData subscript out of bounds

### ISSUE THREAD

**Issue by BakouMert** [GreenGrassBlueOcean/RefinitivR#8] opened 2023-03-13 09:27 UTC
Hi, 
I worked around my problem with RDPsearch usng Excel, so I got the instruments I need. However, sorry to bother you again, when performing a data request from eikon (eikongetdata) my attempts fail. 
code:
d1  <- EikonGetData( EikonObject = Eikon, rics = id
                       , Eikonformulas = c("TR.CommonName;TR.UltimateParent;TR.UltimateParentId;TR.TRBCBusinessSector;TR.TRBCEconomicSector;TR.HeadquartersCountry;TR.UltimateParentCountryHQ;TR.SucceededBy;TR.UltimateSucceededBy;TR.HeadquartersRegion;TR.IsDelistedQuote;TR.CompanyIncorpDate;TR.CompanyPublicSinceDate")
                       , Parameters = list( "CH" = "Fd", "RH"="IN" )
)
data_static <- d1[[1]]

id is a character vector with permID (53.259 of them to be precise). When I sample some of those and perform the data request above for the (much) smaller vector of instruments (I tried n= 3, n=10 and n=20), the code works perfectly. With the full vector it doesn't and gives me the error message below. Would simply splitting up the vector in two or three be a solution? Can the problem be that the numer of id's is too high?

Anyway, I really appreciate your help!

messages:

the operation you intend to perform will cost 53259 data points
[1] "request not ready, server is asking to wait for 12 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 10 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 10 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 10 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 11 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 254 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 13 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 633 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 12 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 499 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 338 seconds so waiting patiently"
[1] 400
[1] "request not ready, server is asking to wait for 747 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 12 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 545 seconds so waiting patiently"
[1] 400
[1] 400
[1] "request not ready, server is asking to wait for 470 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 400 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 393 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 569 seconds so waiting patiently"
[1] 400
[1] "request not ready, server is asking to wait for 365 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 10 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 10 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 13 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 421 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 542 seconds so waiting patiently"
[1] 400
[1] "request not ready, server is asking to wait for 232 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 265 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 365 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 247 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 10 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 211 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 289 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 10 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 499 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 453 seconds so waiting patiently"
Error in data[[requestnumber]][["headers"]][[1]][[x]][["displayName"]] : 
  subscript out of bounds
Calls: sourceWithProgress ... <Anonymous> -> getheaders -> unlist -> lapply -> FUN
Execution halted

**Comment by GreenGrassBlueOcean** [comment] 2023-03-13 09:39
can you send me your ric codes? I would like to replicate this.
It seems that the postprocessing is going wrong somewhere.
As this postprocessing might be different from earlier python Eikon versions it is good to investigate this further

**Comment by BakouMert** [comment] 2023-03-13 10:18
It fails after somwhere around two hours for me (as a background job)

**Comment by BakouMert** [comment] 2023-03-13 10:20
[ID_vector.csv](https://github.com/GreenGrassBlueOcean/RefinitivR/files/10956212/ID_vector.csv)

The code fails after running for around 2 hours as a background job.

**Comment by GreenGrassBlueOcean** [comment] 2023-03-13 10:31
thanks a lot, looking from the error it shows that it has downloaded all. However there are some calls (id) that have resulted in errors (most likely id does not exist). I will take a look at it today. there is also an option to 

raw_output = TRUE, in eikongetdata.
If you use this you will get the raw output that has not been processed to R.
you can then do the processing yourself.

**Comment by GreenGrassBlueOcean** [comment] 2023-03-13 12:15
I was able to reproduce it by using the following:

`
ids <- c("4295908552","4295912121","4295905298",
"4295903247","4295890634","4295903744",
"4295903091","4295904718","4295867384","4295885039",
"5001170594","4298015178","4295903955","4295903051",
"4295912155","4295894770","4295869238","4295894740",
"4295859326","4295885689","4295894791","4295903128",
"5051775617","4295903171","4295899791","4295894777",
"4295903207","4295860844","4295904888","4295860623",
"4295889602","4295903896","4295904216","4295903112", replicate(n=12000, expr = c("WrongRic")))



d1 <- EikonGetData( EikonObject = Eikon
                    , rics = ids
                    , Eikonformulas = c("TR.CommonName;TR.UltimateParent;TR.UltimateParentId;TR.TRBCBusinessSector;TR.TRBCEconomicSector;TR.HeadquartersCountry;TR.UltimateParentCountryHQ;TR.SucceededBy;TR.UltimateSucceededBy;TR.HeadquartersRegion;TR.IsDelistedQuote;TR.CompanyIncorpDate;TR.CompanyPublicSinceDate")
                    , Parameters = list( "CH" = "Fd", "RH"="IN" )
)
data_static <- d1[[1]]`

**Comment by GreenGrassBlueOcean** [comment] 2023-03-14 10:21
I looked into it. This is a server side problem. It has to do with the fact that many of the request you do will not return an answer to the code simply not existing. The best solution is to split the list of ids and use lapply with . EikonGetData Later you can than e.g. use data.table::rbindlist(use.names = TRUE, fill = TRUE) to bind the product to together. you can transform it back to a data.frame with data.table::setDF().

**Comment by BakouMert** [comment] 2023-03-20 14:35
I am trying this now. Given the fact that loops are very slow, I made chunks of 7000 instead of the full 56000, would this be enough? The code is still running but it seems to not go well. I get these messages in the meantime:
[1] "request not ready, server is asking to wait for 3020 seconds so waiting patiently"
[1] "request not ready, server is asking to wait for 560 seconds so waiting patiently"
... 
What does this mean? As I understand it, it is running technically, but as 3020s = 50min it is apparently mostly waiting idly?

**Comment by GreenGrassBlueOcean** [comment] 2023-06-26 14:03
This means that you have asked too many requests to Refinitiv. With each additional request Refinitiv  will increase the response time. I am going to close this issue because this falls within the scope of Refinitiv and not of this package. Please consult the developers forum for additional support.

**Closed** 2023-06-26 14:04 UTC
